### ISSUE TITLE
Request for *Aepelzens Modules* (if possible)

### ISSUE THREAD

**Issue by Atavic** [phdsg/rack-edge#1]
- Can requests be asked?
- If so, I ask for a build of  [*these 6 modules*](https://github.com/Aepelzen/AepelzensModules)
- If not, issue'll be closed

Anyway, :+1:

**Comment by phdsg** [comment]
there you go. i'm probably not gonna update this repo anymore...
[aepelzen-dev-win.zip](https://github.com/phdsg/rack-edge/files/1569738/aepelzen-dev-win.zip)

**Comment by Atavic** [comment]
Many thanks.
