### ISSUE TITLE
Monome build for Windows seems not to work in VCV rack

### ISSUE THREAD

**Issue by Zugelno** [phdsg/rack-edge#2]
It will not start the Monome controller. Input clock signal from external clock does not come out.

**Comment by phdsg** [comment]
weird. works on my side. what version of rack are you using?

**Comment by Zugelno** [comment]
Hello, thanks for fast reply, I am using rack 0.5.1 on W7. I am not a coder, so how do I output that log?
I opened White Wale module and a virtual grid and right clicked on the White Wale module and connected it to the virtual grid, but nothing happens. And when i try to input clock to the White Wale it do not send the clock signal out.
Do you have a patch that contains these modules you could send me?
Many thanks for the binarys.

**Comment by phdsg** [comment]
the log (log.txt) should be in documents/rack.

**Comment by Zugelno** [comment]
Here is the log
[log.txt](https://github.com/phdsg/rack-edge/files/1628349/log.txt)

**Comment by Zugelno** [comment]
And here is the log from fresh install of VCV Rack 0.5.1
[log.txt](https://github.com/phdsg/rack-edge/files/1628379/log.txt)

**Comment by phdsg** [comment]
try renaming the `monome` folder to `monome-rack`.

**Comment by phdsg** [comment]
looks like it's trying to load the firmware from the wrong location. my fault. will fix.

**Comment by Zugelno** [comment]
Ok, many thanks

**Comment by phdsg** [comment]
does it work, if you rename the folder as suggested above?

**Comment by Zugelno** [comment]
No, that didnt help

**Comment by phdsg** [comment]
yeah. i see now. looks like the firmwares aren't included in the dist target at all.

**Comment by phdsg** [comment]
try this: https://github.com/phdsg/rack-edge/blob/master/modules/windows/monome-rack-dev.zip

**Comment by Zugelno** [comment]
That worked ! It seems like that this build is working. The 3 modules lights up and the virtual grids also lights up and advancing steps. Many many thanks for the help. Now its time to learn monome:). Have a nice weekend.
Best from Norway.
